@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Matheus Andrade",
  "email": "matheus@next.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "matheus@next.com",
  "password": "123456"
}

###

# @name create_auction
POST {{baseUrl}}/auctions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{ 
  "bookName": "New Book",
  "description": "LOREM IPSUM",
  "bookImageUrl": "https://images-na.ssl-images-amazon.com/images/I/51Zymoq7UnL._AC_SY400_.jpg",
  "bookGenre": "Fiction"
}


###

# @name fetch_recent_auctions
GET {{baseUrl}}/auctions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name delete_auction
DELETE {{baseUrl}}/auctions/:id
Content-Type: application/json
Authorization: Bearer {{authToken}}